name: Modify and Publish Content

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - '**'
            
jobs:
    modify-content:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout content repository
              uses: actions/checkout@v3

            - name: Clone modifier repository
              uses: actions/checkout@v3
              with:
                  repository: wonderium/content-modified
                  path: content-modified
                  token: ${{ secrets.WD_CONTENT_REPOSITORY_ACCESS_TOKEN }}

            - name: Copy data to modifier/input
              run: |
                  rm -rf content-modified/content/input
                  mkdir -p content-modified/content/input

                  rsync -av --exclude='content-modified' ./* content-modified/content/input

            - name: Install dependencies
              run: |
                  cd content-modified
                  npm install

            - name: Run data processing scripts
              run: |
                  cd content-modified
                  npm run start

            - name: Delete modifier/input
              run: |
                  rm -rf content-modified/content/input
          
            - name: Commit changes to modifier
              run: |
                  cd content-modified
                  git config --global user.name 'github-actions'
                  git config --global user.email 'github-actions@github.com'
                  git add .
                  git commit -m "Adds modified content" || echo "No changes to commit"
                  git push origin main
              env:
                  WD_CONTENT_MODIFIED_ACCESS_TOKEN: ${{ secrets.WD_CONTENT_REPOSITORY_ACCESS_TOKEN }}
